title: Programmering i Videregående Skole
author: René Ask

execute:
  execute_notebooks: force

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - dollarmath
    - amsmath

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/reneaas/vgs_programmering
  path_to_book: docs
  branch: main

launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: true



# html:
#   use_issues_button: true
#   use_repository_button: true

