title: Programmering i Videregående Skole
author: René Ask

execute:
  execute_notebooks: force


latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/reneaas/vgs_programmering
  path_to_book: docs
  branch: main

# html:
#   use_issues_button: true
#   use_repository_button: true

