title: Programmering i Videregående Skole
author: René Ask

execute:
  execute_notebooks: off

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - dollarmath
    - amsmath

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/reneaas/vgs_programmering/
  path_to_book: book/
  branch: main/


launch_buttons:
  notebook_interface: "jupyterlab"  # or "classic"
  binderhub_url: "https://mybinder.org/"
  thebe: true
  colab_url: "https://colab.research.google.com"


html:
  use_issues_button: true
  use_repository_button: true


sphinx:
  extra_extensions:
    - sphinx_proof
    - sphinx_inline_tabs
